version: '3.7'

# Set up all services
services:
  # First the AspNet Core app
  web:
    ## Get the image to use and set the container name
    image: slayrak/test-geocoding:v3
    container_name: test-geocoding
    environment:
    - TestGeocoding_API_KEY=ENTER_API_KEY_HERE

    # State a dependancy on Redis working
    depends_on:
      - "redis_image"

    # Set access ports for localhost on the left
    ports:
      - "8090:80"

    # Configure a link to Redis
    links:
      - "redis_image"

  # The Redis Service, this label is required for the "Links" and Connection string
  redis_image:
    # Pull the image from Docker Hub
    image: redis

    # Give the container a name (any name you want)
    container_name: redis.cache